# Generated by Django 3.1.7 on 2022-12-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='in_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='show_colors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='show_sizes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default='S', max_length=2),
        ),
        migrations.AddField(
            model_name='products',
            name='color',
            field=models.ManyToManyField(to='store.Color'),
        ),
    ]
